PHRASAL_VERBS = [
    # B1
    {"verb": "look forward to", "level": "B1"},
    {"verb": "give up", "level": "B1"},
    {"verb": "put off", "level": "B1"},
    {"verb": "take up", "level": "B1"},
    {"verb": "find out", "level": "B1"},
    {"verb": "turn up", "level": "B1"},
    {"verb": "look after", "level": "B1"},
    {"verb": "get on with", "level": "B1"},
    {"verb": "run out of", "level": "B1"},
    {"verb": "come up with", "level": "B1"},
    # B2
    {"verb": "come across", "level": "B2"},
    {"verb": "carry out", "level": "B2"},
    {"verb": "bring about", "level": "B2"},
    {"verb": "set out", "level": "B2"},
    {"verb": "take on", "level": "B2"},
    {"verb": "draw on", "level": "B2"},
    {"verb": "build up", "level": "B2"},
    {"verb": "break down", "level": "B2"},
    {"verb": "look into", "level": "B2"},
    {"verb": "stand out", "level": "B2"},
    # C1
    {"verb": "account for", "level": "C1"},
    {"verb": "give rise to", "level": "C1"},
    {"verb": "bear out", "level": "C1"},
    {"verb": "set aside", "level": "C1"},
    {"verb": "call for", "level": "C1"},
    {"verb": "fall back on", "level": "C1"},
    {"verb": "play down", "level": "C1"},
    {"verb": "single out", "level": "C1"},
    {"verb": "point to", "level": "C1"},
    {"verb": "rule out", "level": "C1"},
    # C2
    {"verb": "hinge on", "level": "C2"},
    {"verb": "militate against", "level": "C2"},
    {"verb": "impinge on", "level": "C2"},
    {"verb": "bring to bear", "level": "C2"},
    {"verb": "prevail upon", "level": "C2"},
    {"verb": "hold sway over", "level": "C2"},
    {"verb": "brook no", "level": "C2"},
    {"verb": "give way to", "level": "C2"},
    {"verb": "come to terms with", "level": "C2"},
    {"verb": "set store by", "level": "C2"},
]
